config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#index'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post 'users/sign_out',       to: 'devise/sessions#destroy'
    post 'users/guest_sign_in',  to: 'users/sessions#guest_sign_in'
  end

  get 'users/account',    to: 'users#account'
  get 'users/check',      to: 'users#check'
  patch 'users/withdraw', to: 'users#withdraw'

  resources :users, only: [:show]
  resources :posts do
    collection do
      get 'tag_search', to: 'posts#tag_search', as: :tag_search
      get 'keyword_search', to: 'posts#keyword_search', as: :keyword_search
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 250 }
  validates :category, inclusion: { in: ["クラシック", "ロック", "ポップス", "ジャズ", "その他"] }
  validates :tag, presence: true

  def self.search(search)
    return Post.all unless search
    Post.where("title LIKE(?)", "%#{search}%").or(where("category LIKE(?)", "%#{search}%"))
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: "sample@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.username = "ゲスト"
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  validates :username, presence: true
  validates :profile, length: { maximum: 50 }
  validates :guitar_type, length: { maximum: 10 }

  has_one_attached :user_img

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :user_img, :profile, :guitar_type, :years_experience, :category])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require 'google/apis/youtube_v3'

  def find_videos(keyword, after: 2.years.ago, before: Time.now)
    youtube = Google::Apis::YoutubeV3::YouTubeService.new
    youtube.key = Rails.application.credentials.google[:api_key]

    keyword = params[:youtube_search]

    next_page_token = nil

    opt = {
      q: keyword,
      type: "video",
      max_results: 9,
      order: :viewCount,
      page_token: next_page_token,
      published_after: after.iso8601,
      published_before: before.iso8601,
    }

    youtube.list_searches(:snippet, **opt)
  end

  def index
    @posts = Post.all.includes(:user)
  end

  def new
    @post = Post.new
    @user_id = current_user.id
    @youtube_data = find_videos(@keyword)
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to user_path(current_user), notice: "新規投稿をしました"
    else
      redirect_to new_post_path, alert: "未入力の項目があります。"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    @youtube_data = find_videos(@keyword)
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to user_path(current_user), notice: "投稿を更新しました"
    else
      redirect_to edit_post_path, alert: "更新に失敗しました"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(current_user), notice: "投稿を削除しました"
  end

  def tag_search
    @word = params[:word]
    @posts = Post.where(tag: @word)
  end

  def keyword_search
    @posts = Post.search(params[:keyword])
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category, :youtube_url, :tag).merge(user_id: current_user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def after_update_path_for(resource)
    users_account_path(current_user)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def account
    @user = current_user
  end

  def withdraw
    @user = current_user
    if @user.email == "sample@example.com"
      redirect_to :root, alert: "ゲストユーザーは削除できません"
    else
      @user = User.find(current_user.id)
      @user.update(is_deleted: true)
      reset_session
      redirect_to root_path, notice: "退会処理を実行いたしました"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/index.html.erb
<div class="p-5 text-center bg-image", style="background-image: url('<%= asset_path('guitar_top.jpg') %>'); height: 650px">
  <div class="mask" style="background-color: rgba(0, 0, 0, 0.6);">
    <div class="d-flex justify-content-center align-items-center h-100">
      <div>
        <div class="text-white">
          <h1 class="mb-3">集まれ！ギター初心者の集い</h1>
          <p class="mb-3">ギター初心者の集いは初心者みんなでモチベアップを図るための動画共有サイトです。</p>
          <p class="mb-3">気になった動画を検索しよう！</p>
        </div>
        <% if user_signed_in? %>
          <p><%= link_to ">ギター動画を投稿する", new_post_path, class: "btn btn-info btn-lg col-6" %></p>
        <% else %>
          <p><%= link_to ">新規登録はこちら", new_user_registration_path, class: "btn btn-info btn-lg col-6" %></p>
          <%= link_to ">ログインはこちら", new_user_session_path, class: "btn btn-outline-info btn-lg col-5" %>
          <%= link_to ">ゲストログインはこちら", users_guest_sign_in_path, method: :post, class: "btn btn-outline-info btn-lg col-5" %>
        <% end %>
        <div class="text-white">
          <hr class="top-title-hr">
          <p>＼キーワードで投稿を検索／</p>
        </div>
        <%= render "shared/keyword_search_form" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuitarLesson</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.css" rel="stylesheet"/>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.2/mdb.min.js"></script>
  </head>
  <body>
    <%= render "shared/header" %>
    <div class="bg-image", style="background-image: url('<%= asset_path('body-img.jpeg') %>'); height: 100%">
      <%= render "shared/notice" %>
      <%= yield %>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="bg-image", style="background-image: url('<%= asset_path('title-img.jpeg') %>')">
  <div class="title-container">
    <h2>投稿編集</h2>
    <p>投稿した内容を編集できます。</p>
  </div>
</div>
<div class="bg-image", style="padding: 50px 10px">
  <div class="main-container">
    <h3>|投稿内容を編集</h3>
    <%= form_with model: @post do |f| %>
      <table class="table table-sm align-middle mb-3 bg-white">
        <tbody>
          <tr>
            <th>
              <%= f.label :title, "タイトル" %>
              <p>(20文字以内まで)</p>
            </th>
            <td>
              <%= f.text_field :title, size: "40" %>
            </td>
          </tr>
          <tr>
            <th>
              <%= f.label :category, "カテゴリー" %>
            </th>
            <td>
              <%= f.select :category, [["クラシック", "クラシック"], ["ロック", "ロック"], ["ポップス", "ポップス"], ["ジャズ", "ジャズ"], ["その他", "その他"]],
              include_blank: "選択してください" %>
            </td>
          </tr>
          <tr>
            <th>
              <%= f.label :content, "コメント" %>
              <p>(250文字以内まで)</p>
            </th>
            <td>
              <%= f.text_area :content, size: "40x5" %>
            </td>
          </tr>
          <tr>
            <th>
              <%= f.label :tag, "タグ" %>
            </th>
            <td>
              <%= f.text_field :tag %>
            </td>
          </tr>
          <tr>
            <th>
              <%= f.label :youtube_url, "Youtube共有リンク" %>
              <p>(https://youtu.be/ここを入力)</p>
            </th>
            <td>
              <%= f.text_field :youtube_url, size: "40", placeholder: "https://youtu.be/ここを入力" %>
            </td>
          </tr>
        </tbody>
      </table>
      <%= f.hidden_field :user_id, value: @user_id %>
      <div class="actions">
        <%= f.submit "更新する", class: "btn btn-info" %>
        <%= link_to "キャンセル", :back, class: "btn btn-success" %>
      </div>
    <% end %>
    <div style="padding-bottom: 20px">
      <%= form_tag(edit_post_path, method: :get) do %>
        <%= text_field_tag :youtube_search, "", placeholder:"ギター動画を検索" %>
        <%= submit_tag '検索' %>
      <% end %>
    </div>
    <div class="row">
      <% @youtube_data.items.each do |item| %>
        <div class="card-box col-sm-4">
          <div class="card border-dark mb-3">
            <div class="bd-placeholder-img card-img-top">
              <% @snippet = item.snippet %>
              <% @video_id = item.id.video_id %>
              <div class="youtube">
                <div>
                  <iframe src="https://www.youtube.com/embed/<%= @video_id %>"
                  frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
              </div>
              <div class="card-body">
                <p><%= @snippet.title %></p>
                <p>チャンネル名：<%= @snippet.channel_title %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="bg-image", style="background-image: url('<%= asset_path('title-img.jpeg') %>')">
  <div class="title-container">
    <h2>投稿一覧</h2>
    <p>投稿一覧では、他のユーザーが投稿した内容を見ることができます。</p>
    <p>総投稿数：<%= Post.count %><p/>
  </div>
</div>
<div class="bg-image", style="padding: 50px 10px">
  <div class="main-container">
  <div class="input-group">
    <%= render "shared/keyword_search_form" %>
    <%= render "shared/tag_search_form" %>
  </div>
    <%= render "shared/posts_table" %>
  </div>
</div>

app/views/posts/keyword_search.html.erb
<div class="bg-image", style="background-image: url('<%= asset_path('title-img.jpeg') %>')">
  <div class="title-container">
    <h2>投稿検索結果</h2>
    <p>検索結果：<%= @posts.count %>件が見つかりました。<p/>
  </div>
</div>
<div class="bg-image", style="padding: 50px 10px">
  <div class="main-container">
    <div class="input-group">
      <%= render "shared/keyword_search_form" %>
      <%= render "shared/tag_search_form" %>
    </div>
    <%= render "shared/posts_table" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="bg-image", style="background-image: url('<%= asset_path('title-img.jpeg') %>')">
  <div class="title-container">
    <h2><%= @post.title %></h2>
  </div>
</div>
<div class="bg-image", style="padding: 50px 10px">
  <div class="main-container">
    <table class="table align-middle mb-3 bg-white">
      <tbody>
        <tr>
          <th class="fw-bold">アイコン画像</th>
          <td>
            <% if @post.user.user_img.attached? %>
              <%= image_tag @post.user.user_img, class: "rounded-circle", size: "40x40" %>
            <% else %>
              <%= image_tag "default_img.png", class: "rounded-circle", size: "40x40", alt: "Defualt image" %>
            <% end %>
          </td>
        </tr>
        <tr>
          <th class="fw-bold">ユーザー名</th>
          <td><%= @post.user.username %></td>
        </tr>
        <tr>
          <th class="fw-bold">カテゴリー</th>
          <td><%= @post.category %></td>
        </tr>
        <tr>
          <th class="fw-bold">コメント</th>
          <td><%= @post.content %></td>
        </tr>
        <tr>
          <th class="fw-bold">Youtube動画</th>
          <td>
            <% if @post.youtube_url.present? %>
              <div class="youtube">
                <iframe src="https://www.youtube.com/embed/<%= @post.youtube_url %>" allowfullscreen></iframe>
              </div>
            <% else %>
              <p>未設定</p>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <% if user_signed_in? && @post.user_id == current_user.id %>
        <%= link_to "編集する", edit_post_path, class: "btn btn-info" %>
        <%= link_to "削除する", post_path, method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
    <% end %>
    <%= link_to "戻る", :back, class: "btn btn-success" %>
  </div>
</div>

app/views/posts/tag_search.html.erb
<div class="bg-image", style="background-image: url('<%= asset_path('title-img.jpeg') %>')">
  <div class="title-container">
    <h2>投稿検索結果</h2>
    <p>検索結果：<%= @posts.count %>件が見つかりました。<p/>
  </div>
</div>
<div class="bg-image", style="padding: 50px 10px">
  <div class="main-container">
    <div class="input-group">
      <%= render "shared/keyword_search_form" %>
      <%= render "shared/tag_search_form" %>
    </div>
    <%= render "shared/posts_table" %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer-container">
    <p>2023 Copyright:SlowGuitarLife.com</p>
    <hr>
    <p>当サイト上で使用している動画の著作権および商標権、その他知的財産権は当該コンテンツの提供元に帰属します。</p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container-fluid">
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        data-mdb-display="static"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "クラシック", keyword_search_posts_path(keyword: "クラシック"), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ロック", keyword_search_posts_path(keyword: "ロック"), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ポップス", keyword_search_posts_path(keyword: "ポップス"), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ジャズ", keyword_search_posts_path(keyword: "ジャズ"), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= render "shared/keyword_search_form" %>
          </li>
        </ul>
        <div class="d-flex align-items-center">
          <% if user_signed_in? %>
            <div class="dropdown">
              <span
                class="dropdown-toggle align-items-center hidden-arrow"
                id="navbarDropdownMenuAvatar"
                role="button"
                data-mdb-toggle="dropdown"
                aria-expanded="false">
                <% if current_user.user_img.attached? %>
                  <%= image_tag current_user.user_img, class: "rounded-circle", size: "40x40" %>
                <% else %>
                  <%= image_tag "default_img.png", class: "rounded-circle", size: "40x40", alt: "Defualt image" %>
                <% end %>
                <%= "#{current_user.username}" %>
              </span>
              <ul class="dropdown-menu dropdown-menu-sm-end" aria-labelledby="navbarDropdownMenuAvatar">
                <li><%= link_to "マイページ", user_path(current_user), class: "dropdown-item" %></li>
                <li><%= link_to "設定", users_account_path, class: "dropdown-item" %></li>
                <li><%= link_to "投稿する", new_post_path, class: "dropdown-item" %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delite, data: { confirm: "ログアウトしますか？" }, class: "dropdown-item" %></li>
                <li><%= link_to "退会", users_check_path, class: "dropdown-item" %></li>
              </ul>
            </div>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class: "nav-link header-right" %>
            <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-link header-right" %>
            <%= link_to "新規登録", new_user_registration_path, class: "nav-link header-right" %>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_keyword_search_form.html.erb
<div class="input-group mb-2 d-flex justify-content-center">
  <%= form_with url: keyword_search_posts_path, local: true, method: :get do |f| %>
    <%= f.text_field :keyword, placeholder: "投稿名、カテゴリー" %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_notice.html.erb
<div class="Notification">
    <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: key %>
  <% end %>
</div>

app/views/shared/_posts_table.html.erb
<table class="table align-middle mb-0 bg-white">
  <% @posts.each do |post| %>
    <tbody>
      <tr>
        <td>
          <div class="d-flex align-items-center">
            <% if post.user.user_img.attached? %>
              <%= image_tag post.user.user_img, class: "rounded-circle", size: "40x40" %>
            <% else %>
              <%= image_tag "default_img.png", class: "rounded-circle", size: "40x40", alt: "Defualt image" %>
            <% end %>
            <div class="ms-3">
              <p class="fw-bold mb-1"><%= link_to post.user.username, user_path(post.user.id), class: "username_color" %></p>
            </div>
          </div>
        </td>
        <td>
          <p class="fw-normal mb-1"><%= post.title %></p>
        </td>
        <td>
          <p class="fw-normal mb-1">カテゴリー</p>
          <p class="text-muted mb-0"><%= post.category %></p>
        </td>
        <td>
          <p class="fw-normal mb-1">タグ</p>
          <p class="text-muted mb-0"><%= link_to post.tag, tag_search_posts_path(word: post.tag) %></p>
        </td>
        <td>
          <%= post.created_at.to_s(:date_jp) %>
        </td>
        <td>
          <p class="text-muted mb-0"><%= link_to "詳細", post_path(post.id), class: "btn btn-success" %></p>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/shared/_tag_search_form.html.erb
<div class="input-group mb-2 d-flex justify-content-center">
  <%= form_with url: tag_search_posts_path, local: true, method: :get do |f| %>
    <% tag = Post.select(:tag).distinct %>
      <%= f.collection_select(:word, tag, :tag, :tag) %>
      <%= f.submit "タグ検索", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/users/check.html.erb
<div class="bg-image", style="background-image: url('<%= asset_path('title-img.jpeg') %>')">
  <div class="title-container">
    <h2>退会画面</h2>
  </div>
</div>
<div class="bg-image", style="padding:150px 10px; height:500px">
  <div class=main-container>
    <h1>本当に退会しますか？</h1>
    <p>退会する場合は、「退会する」をクリックしてください。</p>
    <%= link_to "退会しない", users_account_path, class: "btn btn-primary ms-3" %>
    <%= link_to "退会する", users_withdraw_path, method: :patch, class: "btn btn-danger ms-3", data: { confirm: "本当に退会しますか？" } %>
  </div>
</div>

app/views/users/show.html.erb
<div class="bg-image", style="background-image: url('<%= asset_path('title-img.jpeg') %>')">
  <div class="title-container">
    <div>
      <% if @user.user_img.attached? %>
        <%= image_tag @user.user_img, class: "rounded-circle", size: "80x80", alt: "ユーザーイメージ" %>
      <% else %>
        <%= image_tag "default_img.png", class: "rounded-circle", size: "80x80", alt: "Defualt image" %>
      <% end %>
    </div>
    <h2 class="fw-bold"><%= @user.username %></h2>
    <p><%= @user.profile %></p>
    <table class="table table-sm">
      <tbody class="table-light">
        <tr>
          <td>
            <p class="fw-normal mb-1">投稿数</p>
            <p class="text-muted mb-0"><%= @posts.count %></p>
          </td>
          <td>
            <p class="fw-normal mb-1">ギターの種類</p>
            <% if @user.guitar_type.present? %>
              <p class="text-muted mb-0"><%= @user.guitar_type %></p>
            <% else %>
              <p class="text-muted mb-0">未設定</p>
            <% end %>
          </td>
          <td>
            <p class="fw-normal mb-1">経験年数</p>
            <% if @user.years_experience.present? %>
              <p class="text-muted mb-0"><%= "#{@user.years_experience}年" %></p>
            <% else %>
              <p class="text-muted mb-0">未設定</p>
            <% end %>
          </td>
          <td>
            <p class="fw-normal mb-1">好きな音楽のジャンル</p>
            <% if @user.category.present? %>
              <p class="text-muted mb-0"><%= @user.category %></p>
            <% else %>
              <p class="text-muted mb-0">未設定</p>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<div class="bg-image", style="padding: 50px 10px">
  <div class="main-container">
    <h3>|<%= @user.username %>の投稿一覧</h3>
    <table class="table table-sm align-middle mb-0 bg-white">
      <% @posts.each do |post| %>
        <tbody>
          <tr>
            <td>
              <div class="d-flex align-items-center">
                <% if post.user.user_img.attached? %>
                  <%= image_tag post.user.user_img, class: "rounded-circle", size: "40x40" %>
                <% else %>
                  <%= image_tag "default_img.png", class: "rounded-circle", size: "40x40", alt: "Defualt image" %>
                <% end %>
                <div class="ms-3">
                  <p class="fw-bold mb-1"><%= post.user.username %></p>
                </div>
              </div>
            </td>
            <td>
              <p class="fw-normal mb-1"><%= post.title %></p>
            </td>
            <td>
              <p class="fw-normal mb-1">カテゴリー</p>
              <p class="text-muted mb-0"><%= post.category %></p>
            </td>
            <td>
              <%= post.created_at.to_s(:date_jp) %>
            </td>
            <td>
              <%= link_to "詳細", post_path(post.id), class: "btn btn-success" %>
              <% user_signed_in? && if post.user_id == current_user.id %>
                <%= link_to "削除", post_path(post.id), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "btn btn-danger" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>